#include "ext_drivers/ams_power_consumer.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#define CHECK(expression) do { if (!(expression)) { \
    fprintf(stderr, "FAIL %s:%d %s\n", __FILE__, __LINE__, #expression); \
    exit(1); } } while (0)

/* These payloads were generated directly by AMS v0.3.4
 * AMS/Core/Src/sop/ams_power_can.c from one fixed power snapshot.  Keeping the
 * producer-generated bytes here makes CAN scale, byte-order, horizon-selection,
 * CRC, and optional-metadata drift visible without coupling ECU CI to the AMS
 * repository at build time. */
static const uint16_t golden_ids[6] = {
    DER26_POWER_DCL_ID,
    DER26_POWER_CCL_ID,
    DER26_POWER_SOH_ID,
    DER26_POWER_ENVELOPE_ID,
    DER26_POWER_STRATEGY_ID,
    DER26_POWER_BINDINGS_ID
};

static const uint8_t golden_counter_5[6][8] = {
    { 0x25u, 0x03u, 0x03u, 0x20u, 0x08u, 0x98u, 0xD1u, 0x49u },
    { 0x25u, 0x03u, 0x00u, 0x64u, 0x01u, 0x2Cu, 0x93u, 0xFDu },
    { 0x25u, 0x5Fu, 0x5Au, 0x78u, 0x53u, 0xCBu, 0xD0u, 0x92u },
    { 0x25u, 0x76u, 0x46u, 0x41u, 0x0Bu, 0x0Au, 0x09u, 0xFDu },
    { 0x25u, 0x35u, 0x4Cu, 0x3Eu, 0x01u, 0x08u, 0x58u, 0x1Eu },
    { 0x25u, 0xECu, 0xBAu, 0x87u, 0x02u, 0x34u, 0x21u, 0x68u }
};

static const uint8_t golden_counter_6[6][8] = {
    { 0x26u, 0x03u, 0x03u, 0x20u, 0x08u, 0x98u, 0xD1u, 0xAEu },
    { 0x26u, 0x03u, 0x00u, 0x64u, 0x01u, 0x2Cu, 0x93u, 0x1Au },
    { 0x26u, 0x5Fu, 0x5Au, 0x78u, 0x53u, 0xCBu, 0xD0u, 0x75u },
    { 0x26u, 0x76u, 0x46u, 0x41u, 0x0Bu, 0x0Au, 0x09u, 0x1Au },
    { 0x26u, 0x35u, 0x4Cu, 0x3Eu, 0x01u, 0x08u, 0x58u, 0xF9u },
    { 0x26u, 0xECu, 0xBAu, 0x87u, 0x02u, 0x34u, 0x21u, 0x8Fu }
};

static void check_crc_vectors(const uint8_t vectors[6][8])
{
    for (uint8_t index = 0u; index < 6u; ++index) {
        CHECK(vectors[index][7] ==
              der26_power_crc8(golden_ids[index], vectors[index]));
    }
}

static void ingest_vector_set(der26_power_consumer_t *consumer,
                              const uint8_t vectors[6][8],
                              uint32_t now_ms)
{
    for (uint8_t index = 0u; index < DER26_POWER_CORE_FRAME_COUNT; ++index) {
        CHECK(der26_power_consumer_ingest(consumer, golden_ids[index], false,
                                          false, 8u, vectors[index],
                                          now_ms + (uint32_t)index));
    }
    CHECK(der26_power_consumer_ingest(consumer, DER26_POWER_STRATEGY_ID,
                                      false, false, 8u, vectors[4],
                                      now_ms + 4u));
    CHECK(der26_power_consumer_ingest(consumer, DER26_POWER_BINDINGS_ID,
                                      false, false, 8u, vectors[5],
                                      now_ms + 5u));
}

int main(void)
{
    der26_power_consumer_t consumer;
    der26_power_immediate_authority_t authority;
    der26_power_feasibility_envelope_t envelope;
    der26_power_resource_state_t resource;
    der26_power_soh_t soh;

    check_crc_vectors(golden_counter_5);
    check_crc_vectors(golden_counter_6);

    der26_power_consumer_init(&consumer);
    ingest_vector_set(&consumer, golden_counter_5, 1000u);
    CHECK(!der26_power_consumer_get_immediate_authority(&consumer, 1006u,
                                                        &authority));
    ingest_vector_set(&consumer, golden_counter_6, 1010u);

    CHECK(der26_power_consumer_get_immediate_authority(&consumer, 1016u,
                                                        &authority));
    CHECK(authority.counter == 6u);
    CHECK(authority.discharge.authorized != 0u);
    CHECK(authority.charge_regen.authorized != 0u);
    CHECK(fabsf(authority.discharge.current_limit_a - 80.0f) < 0.001f);
    CHECK(fabsf(authority.charge_regen.current_limit_a - 10.0f) < 0.001f);
    CHECK(fabsf(authority.discharge.power_limit_w - 22000.0f) < 0.1f);
    CHECK(fabsf(authority.charge_regen.power_limit_w - 3000.0f) < 0.1f);
    CHECK(authority.discharge.binding == 13u);
    CHECK(authority.discharge.limiting_segment == 1u);
    CHECK(authority.charge_regen.binding == 9u);
    CHECK(authority.charge_regen.limiting_segment == 3u);

    CHECK(der26_power_consumer_get_feasibility_envelope(&consumer, 1016u,
                                                        &envelope));
    CHECK(envelope.counter == 6u);
    CHECK(envelope.binding_metadata_valid != 0u);
    CHECK(fabsf(envelope.discharge_constant_current_feasible_a[0] - 118.0f)
          < 0.001f);
    CHECK(fabsf(envelope.discharge_constant_current_feasible_a[1] - 70.0f)
          < 0.001f);
    CHECK(fabsf(envelope.discharge_constant_current_feasible_a[2] - 65.0f)
          < 0.001f);
    CHECK(fabsf(envelope.charge_constant_current_feasible_a[0] - 11.0f)
          < 0.001f);
    CHECK(fabsf(envelope.charge_constant_current_feasible_a[1] - 10.0f)
          < 0.001f);
    CHECK(fabsf(envelope.charge_constant_current_feasible_a[2] - 9.0f)
          < 0.001f);
    CHECK(envelope.discharge_binding[0] == 14u);
    CHECK(envelope.discharge_binding[1] == 12u);
    CHECK(envelope.discharge_binding[2] == 11u);
    CHECK(envelope.charge_binding[0] == 10u);
    CHECK(envelope.charge_binding[1] == 8u);
    CHECK(envelope.charge_binding[2] == 7u);
    CHECK(envelope.discharge_limiting_segment[0] == 0u);
    CHECK(envelope.discharge_limiting_segment[1] == 2u);
    CHECK(envelope.discharge_limiting_segment[2] == 3u);
    CHECK(envelope.charge_limiting_segment[0] == 4u);
    CHECK(envelope.charge_limiting_segment[1] == 2u);
    CHECK(envelope.charge_limiting_segment[2] == 1u);

    CHECK(der26_power_consumer_get_resource_state(&consumer, 1016u,
                                                  &resource));
    CHECK(resource.counter == 6u);
    CHECK(resource.valid != 0u);
    CHECK(resource.mission_profile == 1u);
    CHECK(resource.mission_horizon_index == 1u);
    CHECK(resource.thermal_ready != 0u);
    CHECK(resource.fuse_authority_valid != 0u);
    CHECK(resource.limp_latched == 0u);
    CHECK(resource.mission_fallback == 0u);
    CHECK(resource.r0_bootstrap_progress_pct == 88u);
    CHECK(fabsf(resource.fuse_utilization - 0.76f) < 0.001f);
    CHECK(fabsf(resource.minimum_core_temp_c - 22.0f) < 0.001f);
    CHECK(fabsf(resource.thermal_energy_to_target_wh - 26.4f) < 0.001f);

    CHECK(der26_power_consumer_get_soh(&consumer, 1016u, &soh));
    CHECK(fabsf(soh.capacity_soh - 0.95f) < 0.001f);
    CHECK(fabsf(soh.capacity_soh_lower - 0.90f) < 0.001f);
    CHECK(fabsf(soh.resistance_growth_upper - 1.20f) < 0.001f);
    CHECK(fabsf(soh.combined_soh - 0.83f) < 0.001f);
    CHECK(soh.capacity_confidence_pct == 75u);
    CHECK(soh.resistance_confidence_pct == 80u);
    CHECK(soh.capacity_valid != 0u);
    CHECK(soh.resistance_valid != 0u);

    puts("ams_v034_golden_vector_test PASS");
    return 0;
}
